name: Build Documentation and Examples

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: ./.github/actions/version
        id: latest

      - name: Install LaTeX
        run: |
          sudo apt-get update

          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections

          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-portuguese \
            texlive-science \
            texlive-luatex \
            latexmk \
            ttf-mscorefonts-installer
          
          sudo fc-cache -f -v
          luaotfload-tool --update

      - name: List Arial fonts
        run: |
          fc-list | grep -i arial || true

      - name: Install and Compress siicusp-abstracts.sty
        run: |
          ./scripts/install.sh
          ./scripts/compress.sh

      - run: cp siicusp-abstracts.sty dist/siicusp-abstracts/

      - uses: actions/upload-artifact@v7
        with:
          name: siicusp-abstracts-${{ github.ref_name }}
          path: dist/siicusp-abstracts
          if-no-files-found: error


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: ./.github/actions/version
        id: latest

      - uses: actions/download-artifact@v7
        with:
          name: siicusp-abstracts-${{ github.ref_name }}

      - run: |
          ls -l

  release:
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: siicusp-abstracts-${{ github.ref_name }}
          path: dist

      - name: List artifacts
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          files: |
            dist/siicusp-abstracts-doc.pdf
            dist/siicusp-abstracts-model.pdf
            dist/siicusp-abstracts.sty

  docs:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/download-artifact@v7
        with:
          name: siicusp-abstracts-${{ github.ref_name }}
          path: dist/siicusp-abstracts

      - name: Install Sphinx
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-sphinx

      - name: Build documentation
        run: ./scripts/build-docs.sh
